added a dockerfile and update depedencies
helecz/wkhtmltopdf-microservice pull request #1
Opened 2017-06-01 09:18 UTC by jochen42

2017-06-01 10:30 UTC, pepakriz requested changes
Good job! Thank you very much. I have some questions and ideas, but I'm going to merge it :+1:

2017-06-01 10:30 UTC, pepakriz commented on Dockerfile
> +            --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
why not https variant?

2017-06-01 10:30 UTC, pepakriz commented on Dockerfile
> +RUN apk add --update bash
Maybe this can be installed in first RUN section to reduce docker layers.

BTW: is bash really necessary?

2017-06-01 10:30 UTC, pepakriz commented on Dockerfile
> +COPY . /app
Please copy files just before `npm install`. (https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#build-cache)

2017-06-01 10:30 UTC, pepakriz commented on Dockerfile
> +COPY . /app
and EXPOSE instruction move up for better build process

2017-06-01 12:18 UTC, jochen42 commented on Dockerfile
> +RUN apk add --update bash
yes. node-wkhtmltopdf spawn's it. see https://github.com/devongovett/node-wkhtmltopdf/blob/master/index.js#L201

i will move it to the first RUN

2017-06-01 12:18 UTC, jochen42 commented on Dockerfile
> +COPY . /app
make sense. i will update

2017-06-01 12:18 UTC, jochen42 commented on Dockerfile
> +            --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ \
without reason :) but make's sense. i will update

2017-06-01 12:23 UTC, jochen42 commented
ok. just have a look now...

2017-06-02 05:32 UTC, pepakriz commented
I fixed some typos and formatting issues and now it's in master :+1: 

Thanks!

2017-06-02 05:32 UTC, closed without merging